version: 2
updates:
- package-ecosystem: "docker"
  directory: ".devcontainer"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "08:30"
    timezone: Europe/London
- package-ecosystem: nuget
  directory: "/"
  groups:
    Aspire:
      patterns:
        - Aspire.*
    Microsoft.Extensions:
      patterns:
        - Microsoft.Extensions.*
    OpenTelemetry:
      patterns:
        - OpenTelemetry*
    Polly:
      patterns:
        - Polly*
    Pyroscope:
      patterns:
        - Pyroscope*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "08:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/Costellobot"
  groups:
    babel:
      patterns:
        - "@babel/*"
    faro:
      patterns:
        - "@grafana/faro-web-*"
    typescript-eslint:
      patterns:
        - "@typescript-eslint/*"
  schedule:
    interval: daily
    time: "08:30"
    timezone: Europe/London
  open-pull-requests-limit: 99
