allow-dependencies-licenses:
  - 'pkg:npm/protobufjs'
allow-licenses:
  - '0BSD'
  - 'AGPL-3.0-only AND JSON'
  - 'Apache-2.0'
  - 'BlueOak-1.0.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'CC-BY-4.0'
  - 'CC0-1.0'
  - 'ISC'
  - 'MIT'
  - 'MIT-0'
  - 'Python-2.0'
  - 'Unlicense'
  - '(MIT AND BSD-3-Clause)'
  - '(MIT AND Zlib)'
  - '(MIT OR Apache-2.0)'
  - '(MIT OR CC0-1.0)'
