name: oats

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 3
  TERM: xterm

permissions: {}

jobs:
  oats:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Update agent configuration
        shell: pwsh
        run: |
          $nugetHome = "~/.nuget/packages"
          if (-Not (Test-Path $nugetHome)) {
            New-Item -Path $nugetHome -Type Directory -Force | Out-Null
          }
          $nugetHome = Resolve-Path $nugetHome
          "NUGET_PACKAGES=$nugetHome" >> ${env:GITHUB_ENV}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          cache: false
          go-version: '1.26'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24.x'

      - name: Build container
        id: build
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYROSCOPE_ARCH: 'x86_64'
          PYROSCOPE_VARIANT: 'glibc'
          # renovate: datasource=nuget depName=Pyroscope packageName=Pyroscope
          PYROSCOPE_VERSION: '0.14.2'
          UsePyroscope: 'true'
        run: |
          Write-Output "Downloading Pyroscope..."

          $pyroscope = (gh api "/repos/grafana/pyroscope-dotnet/releases/tags/v${env:PYROSCOPE_VERSION}-pyroscope" | ConvertFrom-Json)
          $pyroscopeAsset = $pyroscope.assets | Where-Object { $_.name -eq "pyroscope.${env:PYROSCOPE_VERSION}-${env:PYROSCOPE_VARIANT}-${env:PYROSCOPE_ARCH}.tar.gz" }
          $pyroscopeUrl = $pyroscopeAsset.browser_download_url

          $archive = Join-Path ${env:RUNNER_TEMP} "pyroscope.tar.gz"
          Invoke-WebRequest -Uri $pyroscopeUrl -OutFile $archive

          Write-Output "Extracting Pyroscope..."

          $targetPath = Join-Path ${env:GITHUB_WORKSPACE} ".pyroscope"
          New-Item -Path $targetPath -Type Directory -Force | Out-Null
          tar -xzf $archive -C $targetPath

          chmod +x (Join-Path $targetPath "Pyroscope.Linux.ApiWrapper.x64.so")
          chmod +x (Join-Path $targetPath "Pyroscope.Profiler.Native.so")

          dotnet publish ./src/Costellobot --arch x64 --os linux -p:PublishProfile=DefaultContainer -p:SetGitHubContainerPublishingOutputs=true

      - name: Tag container
        env:
          CONTAINER_TAG: ${{ steps.build.outputs.container-tag }}
          OATS_TAG: costellobot:latest
        run: docker tag "${CONTAINER_TAG}" "${OATS_TAG}"

      - name: Install OATS
        env:
          # renovate: datasource=github-releases depName=oats packageName=grafana/oats
          OATS_VERSION: v0.6.1
        run: |
          go install "github.com/grafana/oats@${OATS_VERSION}"

      - name: Run OATS
        env:
          # renovate: datasource=github-releases depName=LGTM packageName=grafana/docker-otel-lgtm
          LGTM_VERSION: '0.22.0'
        run: oats --lgtm-version="${LGTM_VERSION}" --timeout=5m ./tests/Costellobot.Oats
